version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - wp_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    volumes:
      - "./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    ports:
      - 9090:80
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - wp_net
  
  wordpress:
    image: wordpress:latest
    container_name: ${APP_NAME}_wordpress
    volumes:
      - wp_data:/var/www/html
      - ./wp-html:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* wpconfig */
        define( 'FS_METHOD', 'direct' );
    depends_on:
      - mysql
    networks:
      - wp_net

  cli:
    image: wordpress:cli
    container_name: ${APP_NAME}_cli
    user: xfs
    volumes:
      - wp_data:/var/www/html:rw
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
      - wordpress
    command: "tail -f /dev/null"
    networks:
      - wp_net

networks:
  wp_net: {}

volumes:
  db_data: {}
  wp_data: {}